### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by RandomDued** [matthewbauer/gametime-player#46]
It is stuck on loading on my site pls fix

**Comment by toolboc** [comment]
I am noticing a similar behavior.  It appears the README is missing instructions for satisfying certain dependencies. 

Error: (SystemJS) load.metadata.sourceMap must be set to an object.
	
	Error loading http://localhost:8080/index.coffee!http://localhost:8080/jspm_packages/github/forresto/system-coffee@0.1.2.js  system.js:5

**Comment by matthewbauer** [comment]
Fixed on master
