### ISSUE TITLE
Missing build.js

### ISSUE THREAD

**Issue by toolboc** [matthewbauer/gametime-player#47]
Build.js is missing and README does not contain instructions on how to produce.

![image](https://user-images.githubusercontent.com/2018336/28696474-62afe754-72fb-11e7-897c-da9cf8faf58b.png)

**Comment by matthewbauer** [comment]
Running ```npm run build``` should create it for you.

But you shouldn't need a build.js if you are running on "master". The gh-pages branch does expect it to be there though.

**Comment by toolboc** [comment]
@matthewbauer , that appears to be a big part of the issue.  'npm run build' does not complete successfully as-is.  Running on Ubuntu 16.04, jspm encounters out of memory errors when attempting to bundle the emulator cores.  Is the build.sh script up to date?

**Comment by matthewbauer** [comment]
Fixed in master
