### ISSUE TITLE
How to map my controller buttons

### ISSUE THREAD

**Issue by Sandwall** [matthewbauer/gametime-player#50]
I have a USB Controller, that looks like a SNES gamepad. It has a turbo button and a clear button for the turbo button. The problem is, I want to play gba games with it, and put the snes B button as the gba A button, and the snes Y button as the gba B button. It won't work how I want it to, so how do I map the buttons. (I made a fork of gametime-player, and I'm playing on that.)

**Comment by Xanderjpg** [comment]
I don't think you can.
