### ISSUE TITLE
Can't "grunt run"

### ISSUE THREAD

**Issue by krazyjakee** [matthewbauer/gametime-player#7]
This project looks awesome but I can't seem to get anything running. There could be a missing grunt file maybe?

`Unable to find local grunt.`

**Comment by matthewbauer** [comment]
It's still a work in progress and I've been changing some things around. If you want to see a working demo you can go to:

http://matthewbauer.us/gametime-player/

Everything is web based now, but as a result performance is pretty bad. Right now I've been looking into ways to improve performance.
